// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vkqwqrnfnfiygygxfnad.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZrcXdxcm5mbmZpeWd5Z3hmbmFkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0MTY0NTMsImV4cCI6MjA3Mjk5MjQ1M30.eeP4SaBmWACVruKOx4sAo7proYE3PgY_6AM-Yo9RLX4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});